//@no-cookie-jar
GET http://localhost:9080/jakartaee-app/api/games
Authorization: Basic YWRtaW46YWRtaW5hZG1pbg==

###
//@no-cookie-jar
GET http://localhost:9080/jakartaee-app/api/games/2cd3be15-c3bd-4df6-8574-62594ded4672

###
//@no-cookie-jar
DELETE http://localhost:9080/jakartaee-app/api/games/2cd3be15-c3bd-4df6-8574-62594ded4672

###
//@no-cookie-jar
POST http://localhost:9080/jakartaee-app/api/games
Authorization: Basic YWRtaW46YWRtaW5hZG1pbg==
Content-Type: application/json

{
  "team1": "t1",
  "team2": "t2",
  "gameDay": "2024-11-04"
}
###
//@no-cookie-jar
PUT http://localhost:9080/jakartaee-app/api/games/d07fd0e3-791c-49cc-870b-4946bf7d828d
Content-Type: application/json

{
  "id": "d07fd0e3-791c-49cc-870b-4946bf7d828d",
  "team1": "nt1",
  "team2": "nt2",
  "gameDay": "2024-11-02"
}
###
//@no-cookie-jar
GET http://localhost:9080/jakartaee-app/api/games/tickets
Authorization: Basic dGVzdDE6dXNlcnVzZXI=

###
//@no-cookie-jar
GET http://localhost:9080/jakartaee-app/api/games/2cd3be15-c3bd-4df6-8574-62594ded4672/tickets

###
//@no-cookie-jar
GET http://localhost:9080/jakartaee-app/api/games/d07fd0e3-791c-49cc-870b-4946bf7d828d/tickets/fa777287-1666-452f-b515-faf164ae235f

###
//@no-cookie-jar
DELETE http://localhost:9080/jakartaee-app/api/games/d07fd0e3-791c-49cc-870b-4946bf7d828d/tickets/fa777287-1666-452f-b515-faf164ae235f

###
//@no-cookie-jar
POST http://localhost:9080/jakartaee-app/api/games/7feb0f27-a572-427a-8a5b-2e47b3b293bb/tickets
Content-Type: application/json

{
  "stake": 111.111,
  "status": false
}
###
//@no-cookie-jar
PUT http://localhost:9080/jakartaee-app/api/games/d07fd0e3-791c-49cc-870b-4946bf7d828d/tickets/fa777287-1666-452f-b515-faf164ae235f
Content-Type: application/json

{
  "id": "fa777287-1666-452f-b515-faf164ae235f",
  "stake": 2222.2222,
  "status": true
}
###
